services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - ./mysql/mysql.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./mysql/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: nest_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: binwise
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: