apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET: supersecret
  JWT_EXPIRES_IN: 1d
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: binwise_user
  DB_PASSWORD: binwise_password
  DB_NAME: binwise